apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: nginx-notes-ingress
  namespace: YourNameSpace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /nginx
        backend:
          service:
            name: ServiceNameOfNginx
            port:
              number: 80

       - pathType: Prefix
        path: /
        backend:
          service:
            name: ServiceNameOfNotesApp
            port:
              number: 8000

