kind: Deployment
apiVersion: apps/v1
metadata:
  name: notesapp-deployment
  namespace: ns-notesapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: notesapp

  template:
    metadata:
      labels:
        app: notesapp

    spec:
      containers:
      - name: notesapp
        image: sumitmandaldockerhub/notes_app:latest
        ports:
        - containerPort: 8000
