kind: Service
apiVersion: v1
metadata:
  name: notesapp-service
  namespace: ns-notesapp
spec:
  selector:
    app: notesapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
